name: 'build-test-zig'
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zig: [ 0.9.1, 0.8.1, master ]
    name: Zig ${{ matrix.zig }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: ${{ matrix.zig }}
      - run: zig build
      - run: zig test src/main.zig
